language: java
dist: trusty
jdk:
  - oraclejdk8
sudo: required
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/bin' -o /tmp/box.zip
- unzip /tmp/box.zip -d /tmp/bin
- sed -i "s/java_args='-client'/java_args='-Xmx512m -client'/" /tmp/bin/box
script:
- ./publish.sh

notifications:
  email: false
